In [1]:
from PIL import Image
import numpy
import torch
import torch.nn as nn
import os

device = "cuda" if torch.cuda.is_available() else "cpu"

In [2]:
class NN(nn.Module) :
    def __init__(self) :
        super().__init__()
        self.f = nn.Sequential(
            nn.Conv2d(in_channels=1,out_channels=16,kernel_size=5), #(1*28*28) -> (16*24*24)
            nn.ReLU(),
            nn.Conv2d(in_channels=16,out_channels=32,kernel_size=5), #(16*24*24) -> (32*20*20)
            nn.ReLU(),
            nn.MaxPool2d(kernel_size=2,stride=2), #(32*20*20) -> (32*10*10)
            nn.Conv2d(in_channels=32,out_channels=64,kernel_size=5), #(32*10*10) -> (64*6*6)
            nn.ReLU(),
            nn.MaxPool2d(kernel_size=2,stride=2), #(64*6*6) -> (64*3*3)
        )
        self.g = nn.Sequential(
            nn.Linear(64*3*3,100),
            nn.ReLU(),
            nn.Linear(100,10),
        )
    def forward(self,x) :
        x = self.f(x)
        x = x.reshape(-1, 64*3*3)
        x = self.g(x)
        return x

In [3]:
F = torch.load("MNIST.pt", weights_only=False)
F = F.to(device)

In [4]:
li = os.listdir("data")
print(li)

['0.png', '1.png', '2.png', '3.png', '4.png', '5.png', '6.png', '7.png', '8.png', '9.png']


In [5]:
for name in li :
    if name.find(".png") < 0 :
        continue
    img = Image.open("data\\"+name)
    img = img.resize((28, 28))
    img = img.convert(mode = "L")
    
    img = numpy.array(img) / 255
    x = torch.tensor(img, dtype = torch.float, device = device).unsqueeze(0)
    y = F(x)
    print((nn.functional.softmax(y,dim=-1) * 100).type(torch.long))
    print("y : ", y.argmax().item())
    print("t : ", name)
    print()

tensor([[93,  0,  0,  0,  0,  0,  0,  0,  0,  5]])
y :  0
t :  0.png

tensor([[ 0, 99,  0,  0,  0,  0,  0,  0,  0,  0]])
y :  1
t :  1.png

tensor([[ 0,  0, 90,  2,  0,  0,  0,  5,  0,  0]])
y :  2
t :  2.png

tensor([[ 0,  0,  0, 99,  0,  0,  0,  0,  0,  0]])
y :  3
t :  3.png

tensor([[ 0,  0,  0,  0, 99,  0,  0,  0,  0,  0]])
y :  4
t :  4.png

tensor([[ 0,  0,  0,  0,  0, 99,  0,  0,  0,  0]])
y :  5
t :  5.png

tensor([[ 0,  0,  0,  0,  0, 37, 61,  0,  0,  0]])
y :  6
t :  6.png

tensor([[ 0, 20, 33,  5,  0,  0,  0, 40,  0,  0]])
y :  7
t :  7.png

tensor([[ 0,  0,  0,  0,  0,  0,  0,  0, 99,  0]])
y :  8
t :  8.png

tensor([[ 0,  0,  0,  0,  0,  0,  0,  0,  0, 99]])
y :  9
t :  9.png

