In [2]:
import torch
import torch.nn as nn

In [4]:
## 문제 1

#1. 텐서 생성
tensor = torch.tensor([-1.0, 0.0, 1.0])
#2. 시그모이드 적용
sigmoid = nn.Sigmoid() #계산하는 객체 생성
output = sigmoid(tensor) #객체에 계산하고 싶은 값 넣어서 결과값
#3. 결과 저장, 출력
print("입력 값 : ",tensor)
print("출력 값 : ",output)

print(1 / (1 + torch.exp(-tensor)))

입력 값 :  tensor([-1.,  0.,  1.])
출력 값 :  tensor([0.2689, 0.5000, 0.7311])
tensor([0.2689, 0.5000, 0.7311])


In [9]:
## 문제 2
# 1. 선형함수 생성
linear_layer = nn.Linear(2, 1)
# 2. 텐서 생성
tensor = torch.randn(1,2)
# 3. 선형함수에 텐서 넣어서 계산
output = linear_layer(tensor)
# 4. 시그모이드 적용
sigmoid = torch.nn.functional.sigmoid(output) #함수 자체에 바로 계산하고 싶은 값 넣어서 결과값
# 5. 결과값 출력
print("입력값 : ", tensor)
print("선형값 : ", output)
print("최종값 : ", sigmoid)

입력값 :  tensor([[-0.0837,  0.3879]])
선형값 :  tensor([[-0.1770]], grad_fn=<AddmmBackward0>)
최종값 :  tensor([[0.4559]], grad_fn=<SigmoidBackward0>)


In [14]:
## 문제 3

# 1.텐서 생성
tensor = torch.tensor([1.0, 0.0, -1.0])
# 2.쌍곡탄젠트 적용
tanh = nn.Tanh()
output = tanh(tensor)
# 3.결과 출력 
print("입력값 : ",tensor)
print("출력값 : ",output)

print((torch.exp(tensor) - torch.exp(-tensor))/(torch.exp(tensor) + torch.exp(-tensor)))

입력값 :  tensor([ 1.,  0., -1.])
출력값 :  tensor([ 0.7616,  0.0000, -0.7616])
tensor([ 0.7616,  0.0000, -0.7616])


In [13]:
## 문제 4

#1. 선형함수 생성
linear_layer = nn.Linear(3,1)
#2. 텐서 생성
tensor = torch.randn(1,3)
#3. 선형함수에 텐서 넣어서 계산
output = linear_layer(tensor)
#4. tanh 적용
tanh = nn.functional.tanh(output)
#5. 결과값 출력
print(tensor)
print(output)
print(tanh)

tensor([[0.4507, 0.5935, 0.6579]])
tensor([[-0.1699]], grad_fn=<AddmmBackward0>)
tensor([[-0.1683]], grad_fn=<TanhBackward0>)


In [15]:
## 문제 1

#1. 텐서 생성
tensor = torch.tensor([-1.0, 2.0, -3.0, 4.0, -5.0])
#2. ReLU에 집어넣고
relu = nn.ReLU()
output = relu(tensor)
#3. 결과값 출력
print("입력값 : ", tensor)
print("출력값 : ", output)

입력값 :  tensor([-1.,  2., -3.,  4., -5.])
출력값 :  tensor([0., 2., 0., 4., 0.])


In [17]:
## 문제 2

#1. 선형 함수 생성
linear_layer = nn.Linear(5,1)
#2. tensor 생성
tensor = torch.randn(1,5)
#3. 선형함수에 tensor 만들어서 계산
output = linear_layer(tensor)
#4. relu 적용
relu = nn.functional.relu(output)
#4. 출력
print("입력 : ",tensor)
print("출력 : ",output)
print("relu : ",relu)

입력 :  tensor([[ 0.9827,  0.7020,  1.5530, -0.4236,  0.0881]])
출력 :  tensor([[-0.4290]], grad_fn=<AddmmBackward0>)
relu :  tensor([[0.]], grad_fn=<ReluBackward0>)


In [20]:
## 문제 3

#1. 텐서 생성
tensor = torch.tensor([2.0,1.0,0.1])
#2. 소프트맥스 적용
softmax = nn.Softmax(dim = -1)
output = softmax(tensor)
#3. 결과 출력
print("입력 : ", tensor)
print("출력 : ", output)
print("출력 전체 합 : ", output.sum())

입력 :  tensor([2.0000, 1.0000, 0.1000])
출력 :  tensor([0.6590, 0.2424, 0.0986])
출력 전체 합 :  tensor(1.0000)


In [25]:
## 문제 4

#1. 선형함수 생성
linear_layer = nn.Linear(4,1)
#2. tensor생성
tensor = torch.randn(1,4)
#3. 선형함수 계산
output = linear_layer(tensor)
#4. softmax적용
softmax = nn.functional.softmax(output, dim = -1)
#5. 출력
print(softmax) #소프트맥스는 다 더하면 1, 즉 하나만 있으면 그것은 1로 고정

tensor([[1.]], grad_fn=<SoftmaxBackward0>)


In [26]:
## 문제 1

#1. 데이터 만들기
y = torch.tensor([2.5,4.0,1.5], dtype = torch.float) #AI가 출력한 값
t = torch.tensor([3.0,4.0,2.0], dtype = torch.float) #실제 값

#2. 손실함수로 비교
loss_function = nn.MSELoss()
loss = loss_function(y, t)

#3. 결과 출력
print(loss)

tensor(0.1667)


In [28]:
## 문제 2

#1. 데이터 만들기
y = torch.tensor([0.2,0.8,0.0], dtype = torch.float) #AI가 출력한 값, 3개의 케이스
t = torch.tensor([0,1,0], dtype = torch.float) #실제 값, 3개의 케이스
#2. 손실함수로 비교 (BCELoss)
loss_function = nn.BCELoss()
loss = loss_function(y, t)
#3. 결과 출력
print(loss)

tensor(0.1488)


In [31]:
## 문제 3

#1. 데이터 만들기
y = torch.tensor([[0.8,0.2],[0.2,0.8],[1.0,0.0]], dtype = torch.float) #AI가 출력한 값 , 3개의 케이스, 원핫 인코딩 형식의 출력값 
t = torch.tensor([0,1,0], dtype = torch.long) #실제 레이블, 3개의 케이스
#2. 손실함수로 비교(CrossEntropyLoss)
loss_function = nn.CrossEntropyLoss()
loss = loss_function(y, t)
#3. 결과 출력
print(loss)

tensor(0.3961)


In [38]:
class sample_function() :
    def __init__(self) :
        pass
    def calculation(self, x) :
        y = 3 * (x ** 2)
        return y
    def grad(self, x) :
        eps = 1e-12
        y = (self.calculation(x + eps) - self.calculation(x)) / eps
        return y

f = sample_function()
x = 3

print("x=3 에서의 함수 출력 : ", f.calculation(x))
print("x=3 에서의 함수 미분 : ", f.grad(x))

# x가 3일때 출력값 : 27
# 도함수 = 6 * x, x가 3일때는 18

x=3 에서의 함수 출력 :  27
x=3 에서의 함수 미분 :  18.001600210482138


In [ ]:
#2에서 -2를 빼면 4니까 

In [41]:
###CrossEntropyLoss에서의 미분

tensor = torch.tensor([[0.1,0.2,0.7]], dtype = torch.float, requires_grad = True)
#tensor값은 AI의 출력값, 0번째는 10%, 1번째는 20%, 2번째는 70%
#requires_grad : 자동 미분 기능 켜는 parameter, 기본값은 False
t = torch.tensor([0], dtype = torch.long)
#실제 정답 라벨값, 실제 정답은 0번째

loss_function = nn.CrossEntropyLoss()
loss = loss_function(tensor, t)

loss.backward() #손실함수 미분

grad = tensor.grad
print(grad)

tensor([[-0.7454,  0.2814,  0.4640]])


In [ ]:
### 확률적 경사하강법(SGD)
# torch에는 이것만 있음
# N개의 case를 넣어서 y값을 출력하고 이걸 N개의 t와 비교하는것
# N개중에 하나만 골라서 이것만 미분해서 경사하강법을 실시하는 것이  SGD

#Batch 경사하강법은
#N개 전부
#SGD만 구현되었지만 case 하나씩 넣어서 순전파 한 다음에 하나씩  SGD를 하면 사실상 전부를 경사하강법 계산 하는것이랑 마찬지지

#MiniBatch 경사하강법은
#N개를 M조각으로 나눠서 나눠서 각각의 조각중에 하나 골라서 미분 (M번 미분)
#SGD만 구현되었지만 DataLoader를 이용해서 case를 나눈다음에 그 조각들을 넣으면 사실상 일부만 선택해서 경사하강법 계산 하는 것이랑 마찬가지

In [45]:
### 임의의 랜덤 데이터 하나 있다하고 이걸 이용해서 가상 AI 하나 만들어 봅시다

#1.x, t입력
x = torch.randn(100,1) #case 100개, feature 1개
t = torch.randn(100,1) #case 100개, 정답 종류 1개
#2.함수들 만들기
F = nn.Sequential(
    nn.Linear(1,1)
)
loss_function = nn.MSELoss() #숫자값 비교
optimizer = torch.optim.SGD(F.parameters(), lr = 0.009) #lr(학습률)을 이용해 미분값 보정
epoch = 10

for e in range(epoch) :
#3.y = F(x)
    y = F(x)
#4.y, t비교
    loss = loss_function(y, t)
#5.F(x) 수정
    optimizer.zero_grad() #미분값 초기화
    loss.backward() #손실함수 미분
    optimizer.step() #신경망 미분&수정

    print(f"epoch {e+1} | loss {loss}")

epoch 1 | loss 0.9206953644752502
epoch 2 | loss 0.9143216013908386
epoch 3 | loss 0.9082117676734924
epoch 4 | loss 0.9023546576499939
epoch 5 | loss 0.8967399597167969
epoch 6 | loss 0.8913574814796448
epoch 7 | loss 0.8861977458000183
epoch 8 | loss 0.8812513947486877
epoch 9 | loss 0.8765097856521606
epoch 10 | loss 0.8719642758369446
