### torch.nn 의 여러 함수들의 기능에 대해

torch.nn.Linear(in_features, out_features, bias) (선형함수) y = xW + b

torch.nn.Conv2d(in_channels, out_channels, kernel_size, stride, padding, bias) (합성곱 함수) y = x*W + b (x와 W는 곱하는거 아님)
kernel_size : W의 크기

torch.nn.RNN(input_size, hidden_size, num_layers, bias, batch_first) (재귀) h = tanh(xW + hW + b)
batch_first == True : (b, s, f)  
batch_first == False : (s, b, f)
b : 문장, s : 단어, f : 단어의 벡터값

In [3]:
import torch
import torch.nn as nn

In [19]:
torch.manual_seed(42)  #랜덤 시드 고정

linear_layer = nn.Linear(10, 1)

input_tensor = torch.tensor([[1,2,3,4,5,6,7,8,9,10]], dtype = torch.float)

linear_output = linear_layer(input_tensor)
print(linear_output)

#시그모이드 함수 적용 0 ~ 1 이이
#functional 모듈 : 함수 계산을 객체 선언없이 바로 하고싶을 때

sigmoid_output1 = torch.nn.functional.sigmoid(linear_output)
print(sigmoid_output1)

sigmoid_function = torch.nn.Sigmoid()
sigmoid_output2 = sigmoid_function(linear_output)
print(sigmoid_output2)


# sigmoid 식 = 1 / (1+exp(-x))
sigmoid_output3 = 1 / (1+torch.exp(-1 * linear_output))
print(sigmoid_output3)

tensor([[2.6147]], grad_fn=<AddmmBackward0>)
tensor([[0.9318]], grad_fn=<SigmoidBackward0>)
tensor([[0.9318]], grad_fn=<SigmoidBackward0>)
tensor([[0.9318]], grad_fn=<MulBackward0>)


In [25]:
torch.manual_seed(9) #시드 고정

linear_layer = nn.Linear(10,1)
input_tensor = torch.randn(1,10) #1행 10열의 랜덤 2차원 tensor 생성 (0-1)

linear_output = linear_layer(input_tensor)
print(linear_output)

#tanh -1 ~ 1 사이의 값
tanh_output = nn.functional.tanh(linear_output)
print(tanh_output)

tanh_function = nn.Tanh()
tanh_output = tanh_function(linear_output)
print(tanh_output)

#tanh = (exp(x) - exp(-x)) / (exp(x) + exp(-x))
tanh_output = (torch.exp(linear_output) - torch.exp(-linear_output)) / (torch.exp(linear_output) + torch.exp(-linear_output))
print(tanh_output)

tensor([[-0.0832]], grad_fn=<AddmmBackward0>)
tensor([[-0.0830]], grad_fn=<TanhBackward0>)
tensor([[-0.0830]], grad_fn=<TanhBackward0>)
tensor([[-0.0830]], grad_fn=<DivBackward0>)


In [35]:
torch.manual_seed(12)

linear_layer = nn.Linear(10,5)
input_tensor = torch.rand(1,10)

linear_output = linear_layer(input_tensor)
print(linear_output)

#ReLU : 양수는 그대로, 음수는 0
ReLU_output = nn.functional.relu(linear_output)
print(ReLU_output)

ReLU = nn.ReLU()
ReLU_output = ReLU(linear_output)
print(ReLU_output)



tensor([[ 0.0657,  0.2302,  0.0756, -0.4304, -0.0321]],
       grad_fn=<AddmmBackward0>)
tensor([[0.0657, 0.2302, 0.0756, 0.0000, 0.0000]], grad_fn=<ReluBackward0>)
tensor([[0.0657, 0.2302, 0.0756, 0.0000, 0.0000]], grad_fn=<ReluBackward0>)


In [39]:
torch.manual_seed(12)

linear_layer = nn.Linear(10,5)
input_tensor = torch.randn(1,10)

linear_output = linear_layer(input_tensor)
print(linear_output)

#LeakyReLU : 양수는 그대로, 음수는 negative_slope 곱한 값
leaky_relu = nn.LeakyReLU(negative_slope=0.01)

print(leaky_relu(linear_output))

tensor([[ 0.4261, -0.3705,  0.8186,  0.0261,  0.8250]],
       grad_fn=<AddmmBackward0>)
tensor([[ 0.4261, -0.0037,  0.8186,  0.0261,  0.8250]],
       grad_fn=<LeakyReluBackward0>)


In [43]:
torch.manual_seed(999)

linear_layer = nn.Linear(10,10)
input_tensor = torch.randn(1,10)

linear_output = linear_layer(input_tensor)
print(linear_output)

# 소프트 맥수 함수 #0~1의 값, 모든 값 합치면 1, 해당 활성화함수는 출력층에서 확률로 변환 할 때 쓰임
softmax = nn.Softmax(dim = 1)
softmax_output = softmax(linear_output)
print(softmax_output)
print("softmax 함수의 전체 합 : ",softmax_output.sum())

tensor([[ 0.4240, -0.2668,  0.6506,  0.7172,  0.4744, -0.8246, -0.7034,  0.3599,
         -0.0691, -0.0794]], grad_fn=<AddmmBackward0>)
tensor([[0.1264, 0.0633, 0.1585, 0.1695, 0.1329, 0.0363, 0.0409, 0.1185, 0.0772,
         0.0764]], grad_fn=<SoftmaxBackward0>)
softmax 함수의 전체 합 :  tensor(1.0000, grad_fn=<SumBackward0>)


In [46]:
linear_layer = nn.Linear(10,1) #1행 1열
input_tensor = torch.randn(1,10) #1행 10열
softmax = nn.Softmax(dim = 1)

print(softmax(linear_layer(input_tensor)))

tensor([[1.]], grad_fn=<SoftmaxBackward0>)


In [52]:
#드랍 아웃 : 함수에서 W를 몇개 비활성화 할지 '비율로' 정하는 수치

dropout = nn.Dropout(p = 0.2)
#20%의 확률로 값을 비활성화 (0으로 만듬), 살아남은 값들은 (1 / (1-p))를 곱해서 값을 보정함
input_data = torch.randn(1,10)

output = dropout(input_data)

print("input data : ", input_data)
print("output data : ", output)

input data :  tensor([[-0.6606,  0.7300,  0.0792, -0.1249,  0.0435, -0.5388, -0.3659, -0.0940,
         -0.5789,  1.0222]])
output data :  tensor([[-0.8258,  0.9125,  0.0991, -0.1562,  0.0544, -0.6735, -0.4573, -0.1175,
         -0.7236,  0.0000]])


In [53]:
#Sequential 신경망 정의

#f(784 > 128) -> ReLU() -> Dropout(0.2) -> g(128 > 64) -> ReLU() -> h(64 > 10) -> Softmax() 로 진행되는 신경망 함수 만기기

F = nn.Sequential(
    nn.Linear(784,128), #f
    nn.ReLU(),
    nn.Dropout(p = 0.2),
    nn.Linear(128,64),
    nn.ReLU(),
    nn.Linear(64,10),
    nn.Softmax()
)

print(F)

Sequential(
  (0): Linear(in_features=784, out_features=128, bias=True)
  (1): ReLU()
  (2): Dropout(p=0.2, inplace=False)
  (3): Linear(in_features=128, out_features=64, bias=True)
  (4): ReLU()
  (5): Linear(in_features=64, out_features=10, bias=True)
  (6): Softmax(dim=None)
)


In [ ]:
## custom 클래스로 위의 Sequential 신경망과 똑같이 작동하는것 만들기

class custom_NN(nn.Module) :
    def __init__(self) :
        super().__init__()
        self.f = nn.Linear(784, 128)
        self.g = nn.Linear(128,64)
        self.h = nn.Linear(64,10)
        self.relu = nn.ReLU()
        self.dropout = nn.Dropout(p = 0.2)
        self.softmax = nn.Softmax()
    def forward(self, x) :
        x = self.f(x)
        x = self.relu(x)
        x = self.dropout(x)
        x = self.g(x)
        x = self.relu(x)
        x = self.h(x)
        x = self.softmax(x)
        return x

In [55]:
##nn.functional 여기서도 객체 선언없이 계산이 가능하다
# 일반 활성화 함수 뿐만 아니라, 노드에 쓰이는 함수들(선형함수, cnn, rnn)같은 것들도 계산이 가능

### functional로 선형함수

input_data = torch.rand(1,3) #1행 3열의 2차원 tensor

weight = torch.rand(2,3)
bias = torch.rand(2)

output = nn.functional.linear(input_data, weight, bias)
print(output)

output = torch.matmul(input_data, weight.T) + bias # y = x*W.T + b
print(output)

tensor([[1.1000, 0.7747]])
tensor([[1.1000, 0.7747]])


In [59]:
linear_layer = nn.Linear(3,2)

for i in linear_layer.parameters() :
    print(i)
    print(i.shape)

Parameter containing:
tensor([[ 0.4512, -0.5088, -0.1428],
        [-0.3730,  0.4167, -0.2049]], requires_grad=True)
torch.Size([2, 3])
Parameter containing:
tensor([-0.1840, -0.1130], requires_grad=True)
torch.Size([2])


In [70]:
### functional로 CNN
input_data = torch.rand(1,1,5,5) #(그림 1장, 색깔채널은 1개, 가로 픽셀 5, 세로 픽셀 5)

weight = torch.rand(16,1,3,3) #(출력 채녈 16개, 갯수 맞춰주는 것 , kernal 가로 픽셀 3, kernel 세로 픽셀 3)

bias = torch.rand(16)

output = nn.functional.conv2d(input_data, weight, bias, stride = 1, padding = 0)
print(output.shape)

torch.Size([1, 16, 3, 3])


In [71]:
### functional로 dropout 구현

torch.manual_seed(999)

input_tensor = torch.randn(3,3)

##dropout은 학습할때는 켜 두고 실제 테스트 할때는 꺼 둡니다.

output1 = nn.functional.dropout(input_tensor, p=0.5, training = True) #training : dropout을 적용할 지 안할 지 판단
print(output1)

output2 = nn.functional.dropout(input_tensor, p=0.5, training = False)
print(output2)

tensor([[-0.0000,  0.9127,  0.0000],
        [-0.0000,  0.0000,  1.9669],
        [-0.3214,  0.0000, -1.2753]])
tensor([[-0.8379,  0.4564,  0.3481],
        [-0.1371,  0.2202,  0.9835],
        [-0.1607,  0.9681, -0.6377]])


In [74]:
torch.manual_seed(12345)

F = nn.Sequential(
    nn.Dropout(p = 0.4)
)

test_tensor = torch.rand(2,5)

F.train() #F 의 Dropout을 활성화, 학습 과정중에 사용
print(F(test_tensor))
F.eval() #F 의 Dropout을 비활성화, 검증 과정중에 사용
print(F(test_tensor))

#신경망 내부에 dropout이 존재하면, dropout을 켜고 끄는 작업이 필요!!!!

tensor([[0.0000, 1.4660, 0.0000, 0.0000, 0.1387],
        [0.2974, 0.0000, 0.9461, 0.0000, 0.0000]])
tensor([[0.9817, 0.8796, 0.9921, 0.4611, 0.0832],
        [0.1784, 0.3674, 0.5676, 0.3376, 0.2119]])


In [82]:
## nn.functional를 이용한 신경망 커스텀 클래스 생성
torch.manual_seed(98765)

class custom_NN(nn.Module) :
    def __init__(self, input_size, output_size) :
        super().__init__()
        self.weight = nn.Parameter(torch.randn(output_size, input_size))
        self.bias = nn.Parameter(torch.randn(output_size))

    def forward(self, x) :
        x = nn.functional.linear(x, self.weight, self.bias) # = x*weight.T + bias
        return x

F = custom_NN(100,10)
loss_function = nn.MSELoss()
optimizer = torch.optim.SGD(F.parameters() ,lr = 0.001)

tensor_x = torch.rand(10,100)
tensor_t = torch.rand(10,10)
epoch = 1000

for e in range(epoch) :
    loss_sum = 0
    for b in range(len(tensor_x)) :
        y = F(tensor_x[b])

        loss = loss_function(y, tensor_t[b])
        loss_sum += loss

        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

    if (e+1) % 100 == 0 :
        print(f"epoch {e+1} || loss {loss_sum / len(tensor_x)}")

epoch 100 || loss 5.5979323387146
epoch 200 || loss 3.913304090499878
epoch 300 || loss 2.7636098861694336
epoch 400 || loss 1.9711214303970337
epoch 500 || loss 1.419503927230835
epoch 600 || loss 1.031815767288208
epoch 700 || loss 0.7567359209060669
epoch 800 || loss 0.5597349405288696
epoch 900 || loss 0.4173768162727356
epoch 1000 || loss 0.31360992789268494
