In [1]:
### torch

import torch
import numpy as np

#url : https://pytorch.org/

### torch AI 만드는 모듈 
수치 계산 딥러닝 AI에서 Featrue(x), 가중치(W) 많으니까 tensor로 묶음
1. 수학에서의 행렬의 명확한 정의는 rank 2의 tensor만 의미
2. rank 1 tensor : vector (vector 의 원소를 차원)
3. rank가 없는 상수 값 : scalar

예 )
[1,2,3,4] : rank 1의 tensor (=vector(4차원))

[1000,2000] : rank 1의 tensor (=vector(2차원))

[[1,3,5],
[2,4,6]] : rank 2의 tensor (=행렬(2행*3열))

[[1],
[2],
[3],
[4]] : rank 2의 tensor (=행렬(4행*1열))

[[999]] : rank 2의 tensor (=행렬(1행*1열))

[
[[0,0,1,0,0],[1,0,0,0,0],[0,0,0,1,0]],
[[0,1,0,0,0],[1,0,0,0,0],[0,0,0,0,1]]
] : rank 3의 tensor

13578 : scalar (상수)

## BUT 저는 수업에서 rank를 정의와 다르게 차원이라 하겠습니다.



In [7]:
### torch에서 tensor 선언(생성하는 법
#[1,2,3] (1 차원 tensor = vector) 의 tensor를 선언해 봅시다

tensor = torch.tensor([1,2,3])
print(tensor)

tensor([1, 2, 3])


In [47]:
### torch에서 신경망 모델 만드는 법 (sequential)
# f(x) (10개 받아서, 5개 출력) -> ReLU() -> g(x) (5개 받아서, 2개 출력)
module = torch.nn.Sequential(
    torch.nn.Linear(in_features = 10, out_features = 5),
    torch.nn.ReLU(),
    torch.nn.Linear(in_features = 5, out_features = 2, bias = False)
)

print(module)

## bias 는 b값이 있는가 없는가의 의미  y = xW + b

Sequential(
  (0): Linear(in_features=10, out_features=5, bias=True)
  (1): ReLU()
  (2): Linear(in_features=5, out_features=2, bias=False)
)


In [17]:
## torch는 GPU(cuda) 기능을 사용할 수 있도록 합니다
# cuda : Nvidia에서 제공하는 GPU 연산 기능

print(torch.cuda.is_available()) #GPU 있는지 찾는것
print(torch.cuda.get_device_name()) #GPU 이름

#생성 tensor를 GPU로 이동

if torch.cuda.is_available() :
    tensor = tensor.to('cuda')

print(tensor)

True
NVIDIA GeForce GTX 1060 3GB
tensor([1, 2, 3], device='cuda:0')


In [41]:
## torch.tensor는 식을 계산하면 자동으로 미분값도 torch class 내부 어딘가에 저장해 놓습니다
## 자동 미분 기능 .backward()

x = torch.tensor(3., requires_grad = True) #requires_grad : 텐서의 자동 미분 기능 켜놓는 parameter (기본값은 False)
y = 3 * x ** 2
y.backward() #식의 자동 미분 함수
print(y)
print(x.grad) #grad : 미분값 출력

tensor(27., grad_fn=<MulBackward0>)
tensor(18.)


In [53]:
### torch에서 신경망 모델 만드는 법 (custom class 사용해서 만드는 법)
class CustomNN(torch.nn.Module) :
    def __init__(self) : #python class 내부의 함수는 선언 할 때에만 self parameter를 맨 앞에 추가
        super().__init__() #python class에서 부모 class의 요소들을 사용하고 싶을 땐 수동으로 부모를 생성자 함수 호출해서 불러와야 함
        #f(10,5) -> g(5,2)
        self.f = torch.nn.Linear(10,5) #f(x) 생성
        self.g = torch.nn.Linear(5,2) #g(x) 생성
        self.h = torch.nn.Sequential(
            torch.nn.Linear(2,20),
            torch.nn.ReLU(),
            torch.nn.Linear(20,5)
        )
    def forward(self, x) : #순전파  x(입력값)가 필요
        x = self.f(x) #f(x)에 x 넣어서 계산 후 결과 값을 x에 덮어쓰기
        x = self.g(x) #g(x)에 x 넣어서 계산 후 결과 값을 x에 덮어쓰기
        x = self.h(x)
        return x

F = CustomNN()

print(F)

module.add_module('customNN', CustomNN()) #기존 신경망에 새 함수들이나 다른 신경망을 이어 붙이는 것도 가능 .add_module()
print(module)

CustomNN(
  (f): Linear(in_features=10, out_features=5, bias=True)
  (g): Linear(in_features=5, out_features=2, bias=True)
  (h): Sequential(
    (0): Linear(in_features=2, out_features=20, bias=True)
    (1): ReLU()
    (2): Linear(in_features=20, out_features=5, bias=True)
  )
)
Sequential(
  (0): Linear(in_features=10, out_features=5, bias=True)
  (1): ReLU()
  (2): Linear(in_features=5, out_features=2, bias=False)
  (customNN): CustomNN(
    (f): Linear(in_features=10, out_features=5, bias=True)
    (g): Linear(in_features=5, out_features=2, bias=True)
    (h): Sequential(
      (0): Linear(in_features=2, out_features=20, bias=True)
      (1): ReLU()
      (2): Linear(in_features=20, out_features=5, bias=True)
    )
  )
)


In [55]:
#텐서의 덧셈 (연산자 + 이용)

a = torch.tensor([2., 3.])
b = torch.tensor([4., 6.])

c = a + b

print(c)
#c는 어떤 값 출력할까요? [6., 9.]

tensor([6., 9.])


In [57]:
#텐서의 덧셈 (함수 이용)
a = torch.tensor([1., 5.])
b = torch.tensor([2., 1.])

c = torch.add(a, b)

print(c)
#c는 어떤 값 출력할까요? [3., 6.]

tensor([3., 6.])


In [65]:
#텐서를 생성할때 list 사용
li = [1,2,3,4,5]
tensor1 = torch.tensor(li)
print(tensor1)

#텐서를 생성할때 numpy.array 사용
import numpy as np
arr = np.array([1,3,5,7,9,11])
tensor2 = torch.tensor(arr)
print(tensor2)

tensor([1, 2, 3, 4, 5])
tensor([ 1,  3,  5,  7,  9, 11], dtype=torch.int32)


In [71]:
#텐서가 가질 수 있는 자료형들
tensor1 = torch.tensor([1,2,3,4,5])
print(tensor1.dtype) # 자료형 : int

tensor2 = torch.tensor([1.0,2.0,3.0,4.0])
print(tensor2.dtype) # 자료형 : float

tensor3 = torch.tensor([True, False, True, False, False])
print(tensor3.dtype) # 자료형 : boolean

tensor4 = tensor1.type(torch.float)
print(tensor4.dtype) # 자료형 : float, torch는 자료형 형변환을 수동으로 다 해줘야 한다

torch.int64
torch.float32
torch.bool
torch.float32


In [77]:
# 자료형 변환 특정 함수들로 형변환 하기

tensor = torch.tensor([0,-1,2,3,4])

float_tensor = tensor.float()
double_tensor = tensor.double()
bool_tensor = tensor.bool()

print(float_tensor, float_tensor.dtype)
print(double_tensor, double_tensor.dtype)
print(bool_tensor, bool_tensor.dtype) # 0이 아니면 전부 True로 바뀜

tensor([ 0., -1.,  2.,  3.,  4.]) torch.float32
tensor([ 0., -1.,  2.,  3.,  4.], dtype=torch.float64) torch.float64
tensor([False,  True,  True,  True,  True]) torch.bool


In [103]:
temp = torch.tensor(-4, dtype = torch.complex64)
tensor = torch.sqrt(temp)
print(tensor, tensor.dtype) # 허수

bool_tensor = tensor.bool()
print(bool_tensor, bool_tensor.dtype)

tensor(0.+2.j) torch.complex64
tensor(True) torch.bool


In [93]:
data = 5

scalar = torch.tensor(data) #0차원 tensor = scalar

print(scalar.shape) #형태
print(scalar.dim()) #차원을 알려주는 함수

torch.Size([])
0


In [97]:
data = [1,3,5,11,9090909] #1차원

vector = torch.tensor(data) #1차원 tensor = vector

print(vector.shape) #형태
print(vector.dim()) #차원 알려주는 함수

torch.Size([5])
1


In [101]:
data = [[1]
        ,[2]
        ,[3]
        ,[4]]

matrix = torch.tensor(data) #2차원 tensor = 행렬(4행*1열)

print(matrix.shape) #형태
print(matrix.dim()) #차원 알려주는 함수

torch.Size([4, 1])
2


In [105]:
data = [
    [[0,0,1,0,0],[1,0,0,0,0],[0,0,0,1,0]]
    ,[[0,1,0,0,0],[1,0,0,0,0],[0,0,0,0,1]]
]

tensor = torch.tensor(data)

print(tensor.shape)
print(tensor.dim()) 

torch.Size([2, 3, 5])
3


In [115]:
# 특정 텐서들 만드는 함수들

#0 tensor
zero_tensor = torch.zeros(2, 3) #2행 3열의 0행렬
print(zero_tensor)

#1 tensor
one_tensor = torch.ones(5, 2) #5행 2열의 1행렬
print(one_tensor)

#특정값으로 모두 채운 tensor
full_tensor = torch.full((4, 3),7) #4행 3열의 행렬을 전부 9로 채우기
print(full_tensor)

#단위행렬 생성
#단위행렬이란 : 정사각행렬(행과 열의 크기가 같은 행렬), 대각선 값이 1이고 나머지가 0인 행렬
eye_tensor = torch.eye(5) #5행 5열의 단위행렬
print(eye_tensor)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]])
tensor([[7, 7, 7],
        [7, 7, 7],
        [7, 7, 7],
        [7, 7, 7]])
tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])


In [119]:
#0부터 20미만까지 4씩 증가하는 수열 생성하기 (vector)
arange_tensor = torch.arange(0,20,4)
print(arange_tensor)

tensor([ 0,  4,  8, 12, 16])


In [123]:
#0부터 12까지 4개의 요수를 균등하게 배치하는 수열 생성하기 (vector, 최솟값은 0, 최댓값은 12, 차원은 4차원)
linspace = torch.linspace(0,30,5) 
print(linspace)

tensor([ 0.0000,  7.5000, 15.0000, 22.5000, 30.0000])


In [127]:
# 난수 생성 tensor
rand_tensor = torch.rand(2,3) #2행 3열의  랜덤 tensor 생성, (random값의 범위는 0-1)
print(rand_tensor)

tensor([[0.1633, 0.9495, 0.1615],
        [0.4645, 0.6222, 0.9246]])


In [135]:
# 난수 생성인데 표준분포를 따르는 random (난수 값들의 표준편차가 1이 되도록 난수 생성)
randn_tensor = torch.randn(4,2) #4행 2열의 랜덤 tensor 생성 (범위 제한은 없는데)
print(randn_tensor)
# 표준편차를 조절하고 싶다
print(randn_tensor * 4) #표준편차 4로 조절

tensor([[-0.0654,  1.1821],
        [ 0.4437,  0.7037],
        [-0.5404, -1.3713],
        [ 1.5572,  1.4867]])
tensor([[-0.2617,  4.7284],
        [ 1.7748,  2.8146],
        [-2.1615, -5.4852],
        [ 6.2290,  5.9469]])


In [137]:
#정수 랜덤을 만들고 싶다
randint_tensor = torch.randint(low = 0, high = 10, size = (2,2)) #0이상 10미만 크기 (2,2) tensor
print(randint_tensor)

tensor([[6, 9],
        [5, 3]])


In [139]:
#랜덤 순열, 0-9까지의 숫자랄 랜덤으로 섞고 싶다
randperm_tensor = torch.randperm(10) #섞고싶은 숫자의 -1을 paramete로 받음
print(randperm_tensor)

tensor([9, 5, 7, 8, 4, 3, 6, 1, 0, 2])


연습문제
1. 행이 4개인 단위행렬 생성하기
2. 모든 원소를 5로 채운 3행 5열의 행렬 생성하기


In [145]:
#1번 문제
eye = torch.eye(4)
print(eye)

full = torch.full((3,5),5)
print(full)

tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])
tensor([[5, 5, 5, 5, 5],
        [5, 5, 5, 5, 5],
        [5, 5, 5, 5, 5]])


In [157]:
## tensor의 형태(차원)를 변경하는 법들

tensor = torch.arange(0,16,1) #vector, 0부터 15까지 16개
print("텐서 : ", tensor)
print("형태 : ", tensor.shape)

#reshape로 4행 4열로 바꿔보기
reshaped = tensor.reshape(4,4) 
print("텐서 : ", reshaped)
print("형태 : ", reshaped.shape)

#view로 4*2*2 3차원으로 바꿔보기
viewed = tensor.view(4,2,2)
print(f"텐서 : {viewed}")
print(f"형태 : {viewed.shape}")

#view, reshape는 기능이 똑같다

텐서 :  tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])
형태 :  torch.Size([16])
텐서 :  tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]])
형태 :  torch.Size([4, 4])
텐서 : tensor([[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]],

        [[ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15]]])
형태 : torch.Size([4, 2, 2])


In [167]:
## tensor의 차원 줄이기
tensor = torch.tensor([[[[1],[2],[3],[4]]]]) #4차원 tensor(1*1*4*1)

#크기가 1인 차원을 전부 제거하는 법
squeezed_tensor = tensor.squeeze()
print(tensor.shape)
print(squeezed_tensor.shape)

#하나만 제거
targeted_squeezed_tensor = tensor.squeeze(0) #첫번째 차원만 제거
print(targeted_squeezed_tensor.shape)

torch.Size([1, 1, 4, 1])
torch.Size([4])
torch.Size([1, 4, 1])


In [171]:
## tensor의 차원 추가
tensor = torch.tensor([1,2,3]) #1차원 tensor(3) = vector

#크기가 1인 차원을 앞에 추가
unsqueezed_tensor1 = tensor.unsqueeze(0)

#크기가 1인 차원을 뒤에 추가
unsqueezed_tensor2 = tensor.unsqueeze(-1)

print(unsqueezed_tensor1)
print(unsqueezed_tensor1.shape)
print(unsqueezed_tensor2)
print(unsqueezed_tensor2.shape)

tensor([[1, 2, 3]])
torch.Size([1, 3])
tensor([[1],
        [2],
        [3]])
torch.Size([3, 1])


In [175]:
# tensor 뒤집기 (Transpose)

tensor = torch.randint(0,20, (2,3,4)) #랜덤으로 0-19까지의 값을 가지는 (2*3*4)크기의 텐서
print(tensor)
print(tensor.shape)

#전체 뒤집고 싶다
print(tensor.T)
print(tensor.T.shape)




tensor([[[ 6,  5, 16, 12],
         [18, 15, 14,  4],
         [13, 11,  1, 12]],

        [[12, 17,  2, 14],
         [14, 14,  3,  8],
         [ 2,  6,  3, 19]]])
torch.Size([2, 3, 4])
tensor([[[ 6, 12],
         [18, 14],
         [13,  2]],

        [[ 5, 17],
         [15, 14],
         [11,  6]],

        [[16,  2],
         [14,  3],
         [ 1,  3]],

        [[12, 14],
         [ 4,  8],
         [12, 19]]])
torch.Size([4, 3, 2])


In [179]:
#특정 값들만 뒤집고 싶다
transposed_tensor = tensor.transpose(0,1) #바꾸고 싶은 차원 두개(1차원, 2차원)만 입력 // 주의: 0부터 세야함
print(transposed_tensor)
print(transposed_tensor.shape)

tensor([[[ 6,  5, 16, 12],
         [12, 17,  2, 14]],

        [[18, 15, 14,  4],
         [14, 14,  3,  8]],

        [[13, 11,  1, 12],
         [ 2,  6,  3, 19]]])
torch.Size([3, 2, 4])


In [183]:
permuted_tensor = tensor.permute(1,0,2) #모든 차원(1차원, 2차원, 3차원)을 바꾸고 싶은 순서대로 적음 // 주의 : 0부터 세야함
print(permuted_tensor)
print(permuted_tensor.shape)

tensor([[[ 6,  5, 16, 12],
         [12, 17,  2, 14]],

        [[18, 15, 14,  4],
         [14, 14,  3,  8]],

        [[13, 11,  1, 12],
         [ 2,  6,  3, 19]]])
torch.Size([3, 2, 4])


In [187]:
## 두 텐서를 이어 붙이고 싶다
tensor1 = torch.tensor([[1,2],[3,4]]) #2차원 (2*2)
tensor2 = torch.tensor([[5,6,7],[8,9,10]]) #2차원 (2*3)

##cat으로 이어 붙이기
cat_tensor = torch.cat((tensor1, tensor2), dim = 1)
print(tensor1)
print(tensor2)
print(cat_tensor)

tensor([[1, 2],
        [3, 4]])
tensor([[ 5,  6,  7],
        [ 8,  9, 10]])
tensor([[ 1,  2,  5,  6,  7],
        [ 3,  4,  8,  9, 10]])


In [191]:
##stack으로 이어 붙이기
tensor1 = torch.tensor([[1,2],[3,4]])
tensor2 = torch.tensor([[5,6],[7,8]])
tensor3 = torch.tensor([[9,10],[11,12]])

stack_tensor = torch.stack((tensor1, tensor2, tensor3), dim = 0)
print(stack_tensor)
print(stack_tensor.shape)

tensor([[[ 1,  2],
         [ 3,  4]],

        [[ 5,  6],
         [ 7,  8]],

        [[ 9, 10],
         [11, 12]]])
torch.Size([3, 2, 2])


In [203]:
## tensor 쪼개기

#chunk로 나누기
tensor = torch.arange(0,20,2) 
print(tensor)

chunks = torch.chunk(tensor, 3, dim=0) #3조각으로 나누기. 3개로 나눴으니까 tuple형태로 나눠짐

print(chunks)

tensor([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])
(tensor([0, 2, 4, 6]), tensor([ 8, 10, 12, 14]), tensor([16, 18]))


In [205]:
#쪼개는 크기를 지정해서 쪼개고 싶어요 (6,2,2)크기를 원해요

split_size = (6,2,2)
splits = tensor.split(split_size, dim = 0)

print(splits)

(tensor([ 0,  2,  4,  6,  8, 10]), tensor([12, 14]), tensor([16, 18]))


In [211]:
## tensor에 조건문 씌어서 특정 값만 출력하기
tensor = torch.arange(0,25,1).reshape(5,5)
print(tensor)

mask = tensor >= 10
print(mask)

#boolean 값 mask를 어떻게 쓰냐면
selected_tensor = tensor[mask] #mask가 True인 원소들만 추출
print(selected_tensor)

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24]])
tensor([[False, False, False, False, False],
        [False, False, False, False, False],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]])
tensor([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24])


In [231]:
y = torch.tensor([[1,2],[3,4]])
gather_index = torch.tensor([[1,1],[1,0]])
gathered = y.gather(1, gather_index)
print(gathered)

tensor([[2, 2],
        [4, 3]])


In [9]:
### tensor를 numpy나 list로 변환하는 방법

#원형 텐서
tensor = torch.tensor([1,2,3,4,5])
print(tensor)
print(type(tensor))

#텐서를 numpy로
numpy_from_tensor = tensor.numpy() #깊은 복사
print(numpy_from_tensor)
print(type(numpy_from_tensor))

#원형 텐서를 수정
print("\n 원형 텐서를 수정함")
tensor = tensor + 3
print(tensor)
print(numpy_from_tensor)
#numpy는 바뀌지 않음

tensor([1, 2, 3, 4, 5])
<class 'torch.Tensor'>
[1 2 3 4 5]
<class 'numpy.ndarray'>

 원형 텐서를 수정함
tensor([4, 5, 6, 7, 8])
[1 2 3 4 5]


In [17]:
#텐서의 복제
original_tensor = torch.tensor([1,2,3,4,5])
cloned_tensor = original_tensor.clone() #깊은 복사 : 값을 복사해서 별개의 객체 생성
# cloned_tensor = original_tensor #얕은 복사 : 참조값(=주소값) 만을 복사

cloned_tensor[0] = 10

print(original_tensor)
print(cloned_tensor)


tensor([1, 2, 3, 4, 5])
tensor([10,  2,  3,  4,  5])


In [23]:
#텐서의 사칙연산에 대해서 알아보자

tensor_a = torch.tensor([[1,2],[3,4]])
tensor_b = torch.tensor([[5,6],[7,8]])

#덧셈
add_result1 = tensor_a + tensor_b
add_result2 = torch.add(tensor_a, tensor_b)
print(add_result1)
print(add_result2)

#뺄셈
sub_result1 = tensor_a - tensor_b
sub_result2 = torch.sub(tensor_a, tensor_b)
print(sub_result1)
print(sub_result2)



tensor([[ 6,  8],
        [10, 12]])
tensor([[ 6,  8],
        [10, 12]])
tensor([[-4, -4],
        [-4, -4]])
tensor([[-4, -4],
        [-4, -4]])


In [31]:
#곱셈
mul_result1 = tensor_a * tensor_b
mul_result2 = torch.mul(tensor_a, tensor_b)
print(mul_result1)
print(mul_result2)
#나눗셈
div_result1 = tensor_a / tensor_b
div_result2 = torch.div(tensor_a, tensor_b)
print(div_result1)
print(div_result2)

tensor([[ 5, 12],
        [21, 32]])
tensor([[ 5, 12],
        [21, 32]])
tensor([[0.2000, 0.3333],
        [0.4286, 0.5000]])
tensor([[0.2000, 0.3333],
        [0.4286, 0.5000]])


In [37]:
### 브로드 케스팅 연산 (차원이 다른 tensor끼리의 연산)

tensor_a = torch.tensor([[1,2,3],[4,5,6]])
tensor_b = torch.tensor([7,8,9])
result = tensor_a + tensor_b

print(result)

tensor([[ 8, 10, 12],
        [11, 13, 15]])


In [51]:
### 텐서별 크기 비교
tensor_a = torch.tensor([5,6,7,8])
tensor_b = torch.tensor([4,6,7,10])

#a가 b보다 크다
gt_result = tensor_a > tensor_b
# gt_result = torch.gt(tensor_a, tensor_b)
print(gt_result)

#a가 b보다 작다
lt_result = tensor_a < tensor_b
# lt_result = torch.lt(tensor_a, tensor_b)
print(lt_result)

#a가 b보다 크거나 같다
ge_result = tensor_a >= tensor_b
# ge_result = torch.ge(tensor_a, tensor_b)
print(ge_result)

#a가 b보다 작거나 같다
le_result = tensor_a <= tensor_b
# le.result - torch.le(tensor_a, tensor_b)
print(le_result)

#a와 b가 같다
eq_result = tensor_a == tensor_b
# eq_result = torch.eq(tensor_a, tensor_b)
print(eq_result)

tensor([ True, False, False, False])
tensor([False, False, False,  True])
tensor([ True,  True,  True, False])
tensor([False,  True,  True,  True])
tensor([False,  True,  True, False])


In [75]:
# tensor 최댓값, 최솟값, 최댓값의 위치, 최솟값의 위치

tensor = torch.tensor([[1,2,3],[4,5,6],[8,9,7]])

#최댓값
max_ = torch.max(tensor)
print(max_)
#최솟값
min_ = torch.min(tensor)
print(min_)

#특정 차원을 기준으로 최댓값
max_, loc_ = torch.max(tensor, dim = 1) #2차원을 기준으로 해당 차원의 최댓값과 그 위치
print(max_, loc_)
min_, loc_ = torch.min(tensor, dim = 1) #2차원을 기주으로 해당 차원의 최댓값과 그 위치
print(min_, loc_)

#argmax, argmin : 위치만 출력
loc_ = torch.argmax(tensor, dim = 1)
print(loc_)
loc_ = torch.argmin(tensor, dim = 1)
print(loc_)

tensor(9)
tensor(1)
tensor([3, 6, 9]) tensor([2, 2, 1])
tensor([1, 4, 7]) tensor([0, 0, 2])
tensor([2, 2, 1])
tensor([0, 0, 2])


In [83]:
tensor = torch.tensor([[1,2,3]
                       ,[4,5,6]
                       ,[7,8,9]])

#전체의 합
total_sum = torch.sum(tensor)
print(total_sum)

#열을 기준으로 한 합
col_sum = torch.sum(tensor, dim=0)
print(col_sum)

#행을 기준으로 한 합
row_sum = torch.sum(tensor, dim=1)
print(row_sum)

tensor(45)
tensor([12, 15, 18])
tensor([ 6, 15, 24])


In [101]:
tensor = torch.tensor([1,2,1,4,5,6,7,9,9], dtype = torch.float)

#평균
mean = torch.mean(tensor)
print(mean)

#중앙값
median = torch.median(tensor)
print(median)

#최빈값
mode, idx = torch.mode(tensor)
print(mode)
print(idx)

tensor(4.8889)
tensor(5.)
tensor(1.)
tensor(2)


In [107]:
#분산과 표준편차
tensor = torch.tensor([1,2,3,4,5], dtype = torch.float)

#분산
var = torch.var(tensor)
print(var)


#표준편차
std = torch.std(tensor)
print(std)
# print(torch.sqrt(var)) #표준편차는 분산에 루트 씌운 것

tensor(2.5000)
tensor(1.5811)


In [117]:
tensor_a = torch.tensor([True, False, True, False])
tensor_b = torch.tensor([True, True, False, False])

#boolean의 논리 연산들
result_and = tensor_a & tensor_b
print(result_and)

result_or = tensor_a | tensor_b
print(result_or)

result_not = ~tensor_a
print(result_not)

tensor([ True, False, False, False])
tensor([ True,  True,  True, False])
tensor([False,  True, False,  True])


In [121]:
tensor = torch.tensor([1,2,3,4], dtype = torch.float)

#지수 연산
exp_result = torch.exp(tensor) # e^tensor
print(exp_result)

#로그 연산
log_result = torch.log(tensor) #log(tensor)
print(log_result)

tensor([ 2.7183,  7.3891, 20.0855, 54.5981])
tensor([0.0000, 0.6931, 1.0986, 1.3863])


In [135]:
#단순 제곱연산
tensor = torch.tensor([1,-2,3,-4], dtype = torch.float)

squared = torch.pow(tensor, exponent = 2) #제곱
print(squared)
cubed = torch.pow(tensor, exponent = 3) #세제곱
print(cubed)

#절댓값 : 음수를 양수로
absolute = torch.abs(tensor)
print(absolute)

#역수 : 곱해서 1이 나오는 수들
reciprocal = torch.reciprocal(tensor)
print(reciprocal)

#기호 바꾸기
neg = torch.neg(tensor)
print(neg)

tensor([ 1.,  4.,  9., 16.])
tensor([  1.,  -8.,  27., -64.])
tensor([1., 2., 3., 4.])
tensor([ 1.0000, -0.5000,  0.3333, -0.2500])
tensor([-1.,  2., -3.,  4.])


In [137]:
#tensor에서 삼각함수 계산하기
#pi = 180도

angle = torch.tensor([0, torch.pi/6, torch.pi/4, torch.pi/3, torch.pi/2])

sin_values = torch.sin(angle)
print(sin_values)

cos_values = torch.cos(angle)
print(cos_values)

tan_values = torch.tan(angle)
print(tan_values)

tensor([0.0000, 0.5000, 0.7071, 0.8660, 1.0000])
tensor([ 1.0000e+00,  8.6603e-01,  7.0711e-01,  5.0000e-01, -4.3711e-08])
tensor([ 0.0000e+00,  5.7735e-01,  1.0000e+00,  1.7321e+00, -2.2877e+07])


In [147]:
#연습문제

a_data = [[1,2,3],
         [4,5,6],
         [7,8,9]]

A = torch.tensor(a_data)

#A에서 2초과 8이하의 값들을 뽑아오려면 어떻게 해야 할까요


answer = A[(A > 2) & (A <=8)] #대괄호 안이 True인 원소들만 출력
print(answer)
print()

print(A > 2)
print(A <= 8)
print((A > 2) & (A <=8))


tensor([3, 4, 5, 6, 7, 8])

tensor([[False, False,  True],
        [ True,  True,  True],
        [ True,  True,  True]])
tensor([[ True,  True,  True],
        [ True,  True,  True],
        [ True,  True, False]])
tensor([[False, False,  True],
        [ True,  True,  True],
        [ True,  True, False]])


In [161]:
#내적 계산 (2차원 vector에서는 행렬계산과 같음)

#벡터(1차원 tensor)의 경우
vector1 = torch.tensor([1,2,3])
vector2 = torch.tensor([4,5,6])
print(vector1 @ vector2) #벡터에서의 내적 = 모든 원소를 곱해서 다 더함
print(torch.dot(vector1, vector2))
#@ 사용해도 되고 torch.dot() 함수 사용해도 됩니다

#행렬(2차원 tensor)의 경우
matrix1 = torch.tensor([[1,2]
                        ,[3,4]]) #2*2 행렬
matrix2 = torch.tensor([[5,6]
                        ,[7,8]]) #2*2 행렬
print(matrix1@matrix2)
# print(torch.dot(matrix1, matrix2)) #사용 불가
print(torch.matmul(matrix1, matrix2))
#@ 사용해도 되고 torch.matmul() 함수 사용해도 됩니다



tensor(32)
tensor(32)
tensor([[19, 22],
        [43, 50]])
tensor([[19, 22],
        [43, 50]])


In [179]:
#3차원 tensor의 경우
tensor1 = torch.tensor([[[1,2],
                       [3,4]],
                       [[5,6],
                       [7,8]]])
tensor2 = torch.tensor([[[1,3],
                       [5,7]],
                       [[2,4],
                       [6,8]]])
print((tensor1@tensor2))
print(torch.matmul(tensor1, tensor2))
#@ 사용해도 되고 torch.matmul() 함수 사용해도 됩니다

tensor([[[11, 17],
         [23, 37]],

        [[46, 68],
         [62, 92]]])
tensor([[[11, 17],
         [23, 37]],

        [[46, 68],
         [62, 92]]])


In [193]:
#자동미분

tensor = torch.tensor(2, dtype = torch.float)
print("자동미분 : ", tensor.requires_grad)
tensor.requires_grad = True
print("자동미분 : ", tensor.requires_grad)

y = tensor ** 2
y.backward()

print("x의 미분값 : ", tensor.grad) #미분값은 scalar (0차원 텐서) 에서만 출력 가능

자동미분 :  False
자동미분 :  True
x의 미분값 :  tensor(4.)


In [201]:
y = tensor ** 2
print("no_grad() 블럭 밖에서의 자동미분 : ", y.requires_grad)

with torch.no_grad() :
    y = tensor ** 2
    print("no_grad() 블럭 내의 자동미분 : ", y.requires_grad)

#자동 미분 기능을 끄는 이유 : 정확도 검증 작업에서 계산 속도 조금이라도 더 빠르게 하기 위해서

no_grad() 블럭 밖에서의 자동미분 :  True
no_grad() 블럭 내의 자동미분 :  False
