In [1]:
import os
import sys
sys.path.append(os.path.join(os.path.dirname(""),".."))

import custom
import numpy
import sklearn
import pickle

In [2]:


with open("ptb.train.txt") as f:
    text = f.readlines()
word_dict, number_dict = custom.make_dict(text)
print(len(word_dict))


9616


In [3]:
corpus = custom.word_num_encoding(text, word_dict)
print(corpus)
print(corpus.shape)

[[   2    3    4 ...    0    0    0]
 [  28   29   30 ...    0    0    0]
 [  42   29   43 ...    0    0    0]
 ...
 [4322 4919   38 ...    0    0    0]
 [  81  831   33 ...    0    0    0]
 [ 112 3581 3582 ...    0    0    0]]
(42068, 98)


In [4]:
comatrix = custom.make_comatrix(corpus, len(word_dict), 2)
print(comatrix)
print(comatrix.shape)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
(9616, 9616)


In [5]:
pmi = custom.make_pmi(comatrix, True)

100%|██████████████████████████████████████████████████████████████████████████████| 9616/9616 [09:02<00:00, 17.74it/s]


In [6]:
U, S, V = sklearn.utils.extmath.randomized_svd(pmi, n_components=100)
#U, S, V = numpy.linalg.svd(pmi)

In [7]:
word_vecs = U[:,:100]
querys = ["you", "year", "car", "toyota"]
for q in querys :
    custom.most_similiar(q, word_dict, number_dict, word_vecs, top = 5)

검색어 || you
anybody : 0.20476273336933964
someone : 0.21310562080037795
something : 0.21485495802161175
ve : 0.21705019678951978
ll : 0.2182388858963091

검색어 || year
earlier : 0.11719101128951963
ending : 0.1315142774060704
period : 0.13279302007270946
fiscal : 0.1359869064388898
june : 0.13610570332110195

검색어 || car
luxury : 0.1405358046162343
vehicle : 0.14787701395992153
auto : 0.14832905751374212
truck : 0.15878490436323311
lexus : 0.1605086420723749

검색어 || toyota
motors : 0.07663946441815997
lexus : 0.07706505166931496
honda : 0.07899646757410717
trails : 0.07923722024671896
eli : 0.08042974072126016



In [9]:
word_vecs = U[:,:100]
querys = ["you", "year", "car", "toyota"]
for q in querys :
    custom.most_similiar(q, word_dict, number_dict, word_vecs, top = 5, mode = "cos")

검색어 || you
i : 0.6892528022517318
anybody : 0.6221309802414643
we : 0.6219012370584684
do : 0.5744455206452496
someone : 0.5437516443068527

검색어 || year
earlier : 0.6972788376988982
month : 0.6836648741228849
last : 0.6322811585933213
next : 0.6181776114114584
ending : 0.5870230200434854

검색어 || car
auto : 0.6471252836214121
luxury : 0.6447017328128396
vehicle : 0.5940508843169175
cars : 0.527911034578664
truck : 0.5196932207631606

검색어 || toyota
motor : 0.6923176263894517
nissan : 0.6650830436674195
motors : 0.6650538916316926
lexus : 0.6107272975473549
honda : 0.5936282808520756



In [8]:
with open("LSA_vector.pkl", mode = "wb") as f:
    pickle.dump(word_vecs, f)