In [1]:
import os
import sys
sys.path.append(os.path.join(os.path.dirname(""),".."))

import custom
import numpy
import sklearn
import pickle

In [2]:


with open("ptb.train.txt") as f:
    text = f.readlines()
word_dict, number_dict = custom.make_dict(text)
print(len(word_dict))


9616


In [3]:
corpus = custom.word_num_encoding(text, word_dict)
print(corpus)
print(corpus.shape)

[[   2    3    4 ...    0    0    0]
 [  28   29   30 ...    0    0    0]
 [  42   29   43 ...    0    0    0]
 ...
 [4322 4919   38 ...    0    0    0]
 [  81  831   33 ...    0    0    0]
 [ 112 3581 3582 ...    0    0    0]]
(42068, 98)


In [4]:
comatrix = custom.make_comatrix(corpus, len(word_dict), 2)
print(comatrix)
print(comatrix.shape)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
(9616, 9616)


In [5]:
pmi = custom.make_pmi(comatrix, True)

100%|██████████████████████████████████████████████████████████████████████████████| 9616/9616 [08:57<00:00, 17.88it/s]


In [6]:
U, S, V = sklearn.utils.extmath.randomized_svd(pmi, n_components=100)
#U, S, V = numpy.linalg.svd(pmi)

In [7]:
word_vecs = U[:,:100]
querys = ["you", "year", "car", "toyota"]
for q in querys :
    custom.most_similiar(q, word_dict, number_dict, word_vecs, top = 5)

In [12]:
word_vecs = U[:,:100]
querys = ["you", "year", "car", "toyota"]
for q in querys :
    result = custom.most_similiar(q, word_dict, number_dict, word_vecs, top = 5, mode = "cos")
    print("검색어 : ", q)
    for r in result :
        print(f"{r[0]} : {r[1]}")
    print()

검색어 :  you
i : 0.6554179409125903
we : 0.6156994571447962
anybody : 0.5976590099480082
else : 0.560103099771577
yourself : 0.5402685041087784

검색어 :  year
month : 0.7032349741997864
period : 0.6717734552776626
earlier : 0.6707900075413255
ending : 0.5951819670540283
next : 0.5895011113767139

검색어 :  car
luxury : 0.7220645503418273
auto : 0.6851632891578503
vehicle : 0.6098784086184947
truck : 0.5725774576846673
corsica : 0.5377983055525232

검색어 :  toyota
motor : 0.726029156807912
motors : 0.6823964121124367
lexus : 0.6244535214566014
nissan : 0.6216516227728542
honda : 0.612464147846379



In [13]:
with open("LSA_vector.pkl", mode = "wb") as f:
    pickle.dump(word_vecs, f)