In [1]:
import os
import sys
sys.path.append(os.path.join(os.path.dirname(""),".."))

import custom
import numpy
import sklearn
import pickle

In [2]:


with open("ptb.train.txt") as f:
    text = f.readlines()
word_dict, number_dict = custom.make_dict(text)
print(len(word_dict))


9616


In [3]:
corpus = custom.word_num_encoding(text, word_dict)
print(corpus)
print(corpus.shape)

[[   2    3    4 ...    0    0    0]
 [  28   29   30 ...    0    0    0]
 [  42   29   43 ...    0    0    0]
 ...
 [4322 4919   38 ...    0    0    0]
 [  81  831   33 ...    0    0    0]
 [ 112 3581 3582 ...    0    0    0]]
(42068, 98)


In [4]:
comatrix = custom.make_comatrix(corpus, len(word_dict), 2)
print(comatrix)
print(comatrix.shape)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
(9616, 9616)


In [5]:
pmi = custom.make_pmi(comatrix, True)

100%|██████████████████████████████████████████████████████████████████████████████| 9616/9616 [08:27<00:00, 18.93it/s]


In [6]:
U, S, V = sklearn.utils.extmath.randomized_svd(pmi, n_components=100)
#U, S, V = numpy.linalg.svd(pmi)

In [7]:
word_vecs = U[:,:100]
querys = ["you", "year", "car", "toyota"]
for q in querys :
    custom.most_similiar(q, word_dict, number_dict, pmi, top = 5)

검색어 || you
i : 0.27373470050470505
we : 0.2578335898033156
do : 0.2364842196040093
they : 0.20343959828188576
if : 0.20331121651452483

검색어 || year
quarter : 0.2042200682823605
next : 0.19196756795265085
last : 0.19109999414394496
this : 0.18053831440167492
n : 0.17889125052038926

검색어 || car
auto : 0.17119188991341888
cars : 0.15146422414076693
luxury : 0.14743425777867786
rental : 0.12003927983498876
competitiveness : 0.10872564434645017

검색어 || toyota
lexus : 0.21690791593926534
honda : 0.18858393587527877
motor : 0.17973048808496025
stanza : 0.17501195066852984
photo : 0.16225440148603826



In [8]:
with open("LSA_vector.pkl", mode = "wb") as f:
    pickle.dump(word_vecs, f)