In [2]:
import os
import sys
sys.path.append(os.path.join(os.path.dirname(""),".."))

import custom
import numpy
import sklearn
import json

In [3]:


with open("ptb.train.txt") as f:
    text = f.readlines()
word_dict, number_dict = custom.make_dict(text)
print(word_dict)


{'<pad>': 0, '<unk>': 1, 'aer': 2, 'banknote': 3, 'berlitz': 4, 'calloway': 5, 'centrust': 6, 'cluett': 7, 'fromstein': 8, 'gitano': 9, 'guterman': 10, 'hydro': 11, 'quebec': 12, 'ipo': 13, 'kia': 14, 'memotec': 15, 'mlx': 16, 'nahb': 17, 'punts': 18, 'rake': 19, 'regatta': 20, 'rubens': 21, 'sim': 22, 'snack': 23, 'food': 24, 'ssangyong': 25, 'swapo': 26, 'wachter': 27, 'pierre': 28, 'unk': 29, 'n': 30, 'years': 31, 'old': 32, 'will': 33, 'join': 34, 'the': 35, 'board': 36, 'as': 37, 'a': 38, 'nonexecutive': 39, 'director': 40, 'nov': 41, 'mr': 42, 'is': 43, 'chairman': 44, 'of': 45, 'v': 46, 'dutch': 47, 'publishing': 48, 'group': 49, 'rudolph': 50, 'and': 51, 'former': 52, 'consolidated': 53, 'gold': 54, 'fields': 55, 'plc': 56, 'was': 57, 'named': 58, 'this': 59, 'british': 60, 'industrial': 61, 'conglomerate': 62, 'form': 63, 'asbestos': 64, 'once': 65, 'used': 66, 'to': 67, 'make': 68, 'kent': 69, 'cigarette': 70, 'filters': 71, 'has': 72, 'caused': 73, 'high': 74, 'percentage': 

In [4]:
corpus = custom.word_num_encoding(text, word_dict)
print(corpus)
print(corpus.shape)

[[   2    3    4 ...    0    0    0]
 [  28   29   30 ...    0    0    0]
 [  42   29   43 ...    0    0    0]
 ...
 [4322 4919   38 ...    0    0    0]
 [  81  831   33 ...    0    0    0]
 [ 112 3581 3582 ...    0    0    0]]
(42068, 98)


In [5]:
comatrix = custom.make_comatrix(corpus, len(word_dict), 2)
print(comatrix)
print(comatrix.shape)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
(9616, 9616)


In [6]:
pmi = custom.make_pmi(comatrix, True)

100%|██████████████████████████████████████████████████████████████████████████████| 9616/9616 [08:36<00:00, 18.62it/s]


In [7]:
U, S, V = sklearn.utils.extmath.randomized_svd(pmi, n_components=100)
#U, S, V = numpy.linalg.svd(pmi)

In [8]:
word_vecs = U[:,:100]
querys = ["you", "year", "car", "toyota"]
for q in querys :
    custom.most_similiar(q, word_dict, number_dict, pmi, top = 5)

검색어 || you
i : 0.27373470050470505
we : 0.2578335898033156
do : 0.2364842196040093
they : 0.20343959828188576
if : 0.20331121651452483

검색어 || year
quarter : 0.2042200682823605
next : 0.19196756795265085
last : 0.19109999414394496
this : 0.18053831440167492
n : 0.17889125052038926

검색어 || car
auto : 0.17119188991341888
cars : 0.15146422414076693
luxury : 0.14743425777867786
rental : 0.12003927983498876
competitiveness : 0.10872564434645017

검색어 || toyota
lexus : 0.21690791593926534
honda : 0.18858393587527877
motor : 0.17973048808496025
stanza : 0.17501195066852984
photo : 0.16225440148603826

