In [1]:
import os
import sys
sys.path.append(os.path.join(os.path.dirname(""),".."))

import custom
import numpy
import pickle
import torch
import torch.nn as nn
from torch.utils.data import DataLoader

In [2]:
with open("ptb.train.txt") as f:
    text = f.readlines()
word_dict, number_dict = custom.make_dict(text)
print(len(word_dict))

9616


In [3]:
corpus = custom.word_num_encoding(text, word_dict)
comatrix = custom.make_comatrix(corpus, len(word_dict), window_size=2)
print(comatrix)
print(comatrix.shape)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
(9616, 9616)


In [4]:
word_pair = custom.make_word_pair(comatrix)
print(word_pair)
print(word_pair.shape)

[[   2    3]
 [   3    2]
 [   2    4]
 ...
 [9576 9574]
 [9580 9581]
 [9581 9580]]
(899500, 2)


In [5]:
device = "cuda" if torch.cuda.is_available() else "cpu"

tensor_x = torch.tensor(word_pair[:,0], dtype = torch.long, device = device)
tensor_t = torch.tensor(word_pair[:,1], dtype = torch.long, device = device)
zip_list = list(zip(tensor_x, tensor_t))
dataloader = DataLoader(zip_list,batch_size=1000,shuffle=True)

tensor_x = None
tensor_t = None
zip_list = None

In [ ]:


class NN(nn.Module) :
    def __init__(self, word_size) :
        super().__init__();
        self.f = nn.Embedding(word_size, 100, max_norm=1, padding_idx=0)
        self.g = nn.Linear(100, word_size)
    def forward(self, x) :
        y = self.f(x)
        y = self.g(y)
        return y

F = NN(len(word_dict))
F = F.to(device)
loss_function = nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(F.parameters(), lr = 0.05)
epoch = 10

for e in range(epoch) :
    loss_sum = 0
    for x, t in dataloader :
        y = F(t)
    
        loss = loss_function(y, t)
        loss_sum += loss
        
        loss.backward()
        optimizer.step()
        optimizer.zero_grad()
    loss_sum /= len(dataloader)
    
    if (e+1) % 1 == 0 :
        print("epoch {} | loss {}".format(e+1, loss_sum))


epoch 1 | loss 5.32411003112793
epoch 2 | loss 0.5091938376426697
epoch 3 | loss 0.026756318286061287


In [ ]:
F.to("cpu")
word_vecs = F.state_dict()['f.weight'].numpy()

print(word_vecs.shape)
print(word_vecs)

In [ ]:
word_vecs = word_vecs.tolist()
vector_dict = {}
words = list(word_dict.keys())

for i in (len(word_vecs))
    vector_dict[words[i]] = word_vecs[i]

print(vector_dict)

In [ ]:
with open("word2vec_vector.pkl", mode = "wb") as f :
    pickle.dump(word_vecs, f)