In [1]:
import custom
import numpy
import sklearn
import json

In [2]:
window_size = 2

with open("ptb.train.txt") as f:
    text = f.readlines()
word_dict, number_dict = custom.make_dict(text)
print(word_dict)


{'<eos>': 0, '<unk>': 1, 'aer': 2, 'banknote': 3, 'berlitz': 4, 'calloway': 5, 'centrust': 6, 'cluett': 7, 'fromstein': 8, 'gitano': 9, 'guterman': 10, 'hydro-quebec': 11, 'ipo': 12, 'kia': 13, 'memotec': 14, 'mlx': 15, 'nahb': 16, 'punts': 17, 'rake': 18, 'regatta': 19, 'rubens': 20, 'sim': 21, 'snack-food': 22, 'ssangyong': 23, 'swapo': 24, 'wachter': 25, 'pierre': 26, 'n': 27, 'years': 28, 'old': 29, 'will': 30, 'join': 31, 'the': 32, 'board': 33, 'as': 34, 'a': 35, 'nonexecutive': 36, 'director': 37, 'nov': 38, '.': 39, 'mr': 40, 'is': 41, 'chairman': 42, 'of': 43, '.v': 44, 'dutch': 45, 'publishing': 46, 'group': 47, 'rudolph': 48, 'and': 49, 'former': 50, 'consolidated': 51, 'gold': 52, 'fields': 53, 'plc': 54, 'was': 55, 'named': 56, 'this': 57, 'british': 58, 'industrial': 59, 'conglomerate': 60, 'form': 61, 'asbestos': 62, 'once': 63, 'used': 64, 'to': 65, 'make': 66, 'kent': 67, 'cigarette': 68, 'filters': 69, 'has': 70, 'caused': 71, 'high': 72, 'percentage': 73, 'cancer': 7

In [10]:
corpus = custom.word_num_encoding(text, word_dict)
print(corpus)

[[   2    3    4 ...   -1   -1   -1]
 [  26    1   27 ...   -1   -1   -1]
 [  40   39    1 ...   -1   -1   -1]
 ...
 [4408 5022   35 ...   -1   -1   -1]
 [  79  840   30 ...   -1   -1   -1]
 [ 109 3636 3637 ...   -1   -1   -1]]


In [11]:
comatrix = custom.make_comatrix(corpus, len(word_dict), 2)
print(comatrix)

[[0.0000e+00 0.0000e+00 0.0000e+00 ... 0.0000e+00 0.0000e+00 0.0000e+00]
 [0.0000e+00 1.4696e+04 0.0000e+00 ... 0.0000e+00 1.0000e+00 1.0000e+00]
 [0.0000e+00 0.0000e+00 0.0000e+00 ... 0.0000e+00 0.0000e+00 0.0000e+00]
 ...
 [0.0000e+00 0.0000e+00 0.0000e+00 ... 0.0000e+00 0.0000e+00 0.0000e+00]
 [0.0000e+00 1.0000e+00 0.0000e+00 ... 0.0000e+00 0.0000e+00 0.0000e+00]
 [0.0000e+00 1.0000e+00 0.0000e+00 ... 0.0000e+00 0.0000e+00 0.0000e+00]]


In [12]:
pmi = custom.make_pmi(comatrix, True)

0.0% 완료
0.0% 완료
0.0% 완료
0.0% 완료
0.1% 완료
0.1% 완료
0.1% 완료
0.1% 완료
0.1% 완료
0.1% 완료
0.1% 완료
0.1% 완료
0.1% 완료
0.1% 완료
0.2% 완료
0.2% 완료
0.2% 완료
0.2% 완료
0.2% 완료
0.2% 완료
0.2% 완료
0.2% 완료
0.2% 완료
0.2% 완료
0.3% 완료
0.3% 완료
0.3% 완료
0.3% 완료
0.3% 완료
0.3% 완료
0.3% 완료
0.3% 완료
0.3% 완료
0.3% 완료
0.4% 완료
0.4% 완료
0.4% 완료
0.4% 완료
0.4% 완료
0.4% 완료
0.4% 완료
0.4% 완료
0.4% 완료
0.4% 완료
0.5% 완료
0.5% 완료
0.5% 완료
0.5% 완료
0.5% 완료
0.5% 완료
0.5% 완료
0.5% 완료
0.5% 완료
0.5% 완료
0.6% 완료
0.6% 완료
0.6% 완료
0.6% 완료
0.6% 완료
0.6% 완료
0.6% 완료
0.6% 완료
0.6% 완료
0.6% 완료
0.7% 완료
0.7% 완료
0.7% 완료
0.7% 완료
0.7% 완료
0.7% 완료
0.7% 완료
0.7% 완료
0.7% 완료
0.7% 완료
0.8% 완료
0.8% 완료
0.8% 완료
0.8% 완료
0.8% 완료
0.8% 완료
0.8% 완료
0.8% 완료
0.8% 완료
0.8% 완료
0.9% 완료
0.9% 완료
0.9% 완료
0.9% 완료
0.9% 완료
0.9% 완료
0.9% 완료
0.9% 완료
0.9% 완료
0.9% 완료
1.0% 완료
1.0% 완료
1.0% 완료
1.0% 완료
1.0% 완료
1.0% 완료
1.0% 완료
1.0% 완료
1.0% 완료
1.0% 완료
1.1% 완료
1.1% 완료
1.1% 완료
1.1% 완료
1.1% 완료
1.1% 완료
1.1% 완료
1.1% 완료
1.1% 완료
1.1% 완료
1.2% 완료
1.2% 완료
1.2% 완료
1.2% 완료
1.2% 완료
1.2% 완료
1.2% 완료
1.2% 완료
1.2% 완료
1.2% 완료
1.3% 완료


In [19]:
U, S, V = sklearn.utils.extmath.randomized_svd(pmi, n_components=100)
word_vecs = U[:,:100]

In [20]:
querys = ["you", "year", "car", "toyota"]
for q in querys :
    custom.most_similiar(q, word_dict, number_dict, word_vecs, top = 5)

검색어 || you
i : 0.6577763271378039
we : 0.6048539690002063
someone : 0.55351533735157
'll : 0.5522441871715851
anybody : 0.5328239477791921

검색어 || year
month : 0.6959243456009354
earlier : 0.6730948665373289
next : 0.6305130978848285
last : 0.620089832449405
quarter : 0.6031196365804877

검색어 || car
auto : 0.6550529612101531
luxury : 0.6309207756424813
truck : 0.5842442497744145
vehicle : 0.5812239880828877
domestic : 0.5738765197959067

검색어 || toyota
motor : 0.6556364097254879
motors : 0.5957166014317328
nissan : 0.5852832993342231
honda : 0.577045500777439
grumman : 0.5347910026678281



In [3]:
with open("word_dict.json", "w") as f:
    json.dump(word_dict, f)