In [1]:
import torch
import torch.nn as nn

In [2]:
rnn = nn.RNN(5,3,batch_first = True, bidirectional = True, num_layers = 2)

In [3]:
x = torch.randn(1,2,5)
y, h = rnn(x)

print(y)
print(h)

tensor([[[-0.6856, -0.5147, -0.7547,  0.0339,  0.8284,  0.1965],
         [-0.1969, -0.6126, -0.4921,  0.0496,  0.5074,  0.1886]]],
       grad_fn=<TransposeBackward1>)
tensor([[[ 0.7280,  0.1446,  0.9123]],

        [[-0.8551,  0.7618, -0.6513]],

        [[-0.1969, -0.6126, -0.4921]],

        [[ 0.0339,  0.8284,  0.1965]]], grad_fn=<StackBackward0>)


In [7]:
h_forward = h[::2]
h_backward = h[1::2]

print(h_forward)
print(h_backward)

new_h = h_forward + h_backward
print(new_h)

print(new_h.mean(dim = 0))

tensor([[[ 0.7280,  0.1446,  0.9123]],

        [[-0.1969, -0.6126, -0.4921]]], grad_fn=<SliceBackward0>)
tensor([[[-0.8551,  0.7618, -0.6513]],

        [[ 0.0339,  0.8284,  0.1965]]], grad_fn=<SliceBackward0>)
tensor([[[-0.1271,  0.9064,  0.2610]],

        [[-0.1631,  0.2158, -0.2956]]], grad_fn=<AddBackward0>)
tensor([[-0.1451,  0.5611, -0.0173]], grad_fn=<MeanBackward1>)
