In [1]:
import torch
import torch.nn as nn

In [2]:
rnn = nn.RNN(5,3,batch_first = True, bidirectional = True, num_layers = 2)

In [3]:
x = torch.randn(2,3,5)
y, h = rnn(x)

print(y)
print(h.permute(1,0,2))

tensor([[[ 0.1319,  0.7672, -0.3622, -0.7937,  0.2348,  0.8363],
         [-0.4497,  0.0440,  0.6871, -0.5716,  0.6775, -0.1743],
         [-0.3545,  0.5942,  0.7546, -0.4184,  0.2521, -0.3916]],

        [[-0.4405,  0.5250, -0.1028, -0.0992, -0.3538,  0.2637],
         [-0.3758,  0.3292,  0.4154, -0.7774,  0.4615,  0.1255],
         [-0.0990,  0.3328,  0.0657, -0.8148,  0.6041,  0.4332]]],
       grad_fn=<TransposeBackward1>)
tensor([[[ 0.9940, -0.7825,  0.8266],
         [-0.9406, -0.7522,  0.2524],
         [-0.3545,  0.5942,  0.7546],
         [-0.7937,  0.2348,  0.8363]],

        [[ 0.2655, -0.1487,  0.9430],
         [ 0.3823, -0.2087, -0.1228],
         [-0.0990,  0.3328,  0.0657],
         [-0.0992, -0.3538,  0.2637]]], grad_fn=<PermuteBackward0>)


In [8]:
hf = h[::2]
hb = h[1::2]
new_h = torch.cat([hf, hb], dim = -1).permute(1,0,2).mean(dim = 1).unsqueeze(dim = 1) # peeky 알고리즘

print(torch.cat([hf, hb], dim = -1).permute(1,0,2))
print(new_h)

tensor([[[ 0.9940, -0.7825,  0.8266, -0.9406, -0.7522,  0.2524],
         [-0.3545,  0.5942,  0.7546, -0.7937,  0.2348,  0.8363]],

        [[ 0.2655, -0.1487,  0.9430,  0.3823, -0.2087, -0.1228],
         [-0.0990,  0.3328,  0.0657, -0.0992, -0.3538,  0.2637]]],
       grad_fn=<PermuteBackward0>)
tensor([[[ 0.3197, -0.0942,  0.7906, -0.8672, -0.2587,  0.5444]],

        [[ 0.0832,  0.0921,  0.5043,  0.1416, -0.2812,  0.0705]]],
       grad_fn=<UnsqueezeBackward0>)
