In [1]:
from PIL import Image
import numpy
import torch
import torch.nn as nn
import os

device = "cuda" if torch.cuda.is_available() else "cpu"

In [3]:
F = torch.load("MNIST.pt", weights_only=False)
F = F.to(device)

In [4]:
li = os.listdir("data")
print(li)

['0.png', '1.png', '2.png', '3.png', '4.png', '5.png', '6.png', '7.png', '8.png', '9.png']


In [6]:
for name in li :
    if name.find(".png") < 0 : 
        continue
    img = Image.open("data\\"+name)
    img = img.resize((28, 28))
    img = img.convert(mode = "L")
    
    img = numpy.array(img) / 255
    x = torch.tensor(img, dtype = torch.float, device = device).reshape(-1,28*28)
    y = F(x)
    print((nn.functional.softmax(y,dim=-1) * 100).type(torch.long))
    print("y : ", y.argmax().item())
    print("t : ", name)
    print()

tensor([[43,  0,  1,  0,  0,  0,  0,  4,  0, 48]])
y :  9
t :  0.png

tensor([[ 0, 83,  2,  0,  6,  0,  0,  4,  1,  0]])
y :  1
t :  1.png

tensor([[ 0,  0, 58, 11,  0,  0,  0, 29,  0,  0]])
y :  2
t :  2.png

tensor([[ 0,  0,  2, 69,  9,  1,  0,  9,  1,  4]])
y :  3
t :  3.png

tensor([[ 0,  0,  2,  0, 95,  0,  0,  1,  0,  0]])
y :  4
t :  4.png

tensor([[ 0,  0,  0,  0,  0, 99,  0,  0,  0,  0]])
y :  5
t :  5.png

tensor([[ 3,  0, 11,  0,  0, 64, 11,  0,  8,  0]])
y :  5
t :  6.png

tensor([[ 0, 13, 78,  1,  0,  0,  0,  2,  2,  0]])
y :  2
t :  7.png

tensor([[ 0,  0,  0,  0,  0,  0,  0,  0, 98,  0]])
y :  8
t :  8.png

tensor([[ 0,  0,  0,  1,  0,  0,  0,  1,  1, 95]])
y :  9
t :  9.png

