In [1]:
import torch

In [12]:
F = torch.nn.RNN(5,3,num_layers = 6,batch_first = True)

x = torch.tensor([
    [[1,0,0,0,0],
    [0,1,0,0,0]],
    [[0,0,0,1,0],
    [0,0,0,0,1]]    
], dtype = torch.float)

y, h = F(x)

print(y)
print()
print(h)
print()
print(h.shape)


a = y[:,0:1,:]
print(a)
print(a.shape)

tensor([[[ 0.0371, -0.1100, -0.1617],
         [ 0.0720, -0.2431, -0.0763]],

        [[ 0.0289, -0.1195, -0.1923],
         [ 0.0645, -0.2612, -0.0852]]], grad_fn=<TransposeBackward1>)

tensor([[[ 0.0361, -0.3131,  0.7559],
         [ 0.0337, -0.1667,  0.8530]],

        [[-0.1600,  0.5044,  0.7831],
         [-0.2545,  0.4798,  0.8253]],

        [[-0.8996,  0.6347,  0.6875],
         [-0.8996,  0.6412,  0.6646]],

        [[ 0.3043, -0.6666, -0.1917],
         [ 0.2913, -0.6656, -0.1934]],

        [[-0.0974,  0.6591, -0.0695],
         [-0.1083,  0.6529, -0.0765]],

        [[ 0.0720, -0.2431, -0.0763],
         [ 0.0645, -0.2612, -0.0852]]], grad_fn=<StackBackward0>)

torch.Size([6, 2, 3])
tensor([[[ 0.0371, -0.1100, -0.1617]],

        [[ 0.0289, -0.1195, -0.1923]]], grad_fn=<SliceBackward0>)
torch.Size([2, 1, 3])
